### ISSUE TITLE
2.0 API proposal

### ISSUE THREAD

**Issue by dfcreative** [audiojs/audio-speaker#42]
Ideally API should be 

```js
const Speaker = require('audio-speaker')
let write = Speaker(options)
write(audioBuffer|data, callback)
```

**Comment by connorhartley** [comment]
The issue regarding the proposal for 2.0 is as follows.

We can either run with the current version of `audio-mpg123` which is basically ready for release, just need to split up the projects of course.

Or we could wait until the NAPI version of `audio-mpg123` is complete. Then make changes the API to follow the changes in `audio-mpg123` then release.

Although the issue with releasing now is, the changes that will come with updating to the NAPI `audio-mpg123`. I suggest we could deprecate the methods and add newer methods for it that work better with ArrayBuffers for instance.

The issue with waiting for the NAPI version is that there would be a fairly long wait until NAPI is stable and ready to be used on production. To use NAPI modules they require the NAPI flag to add the dependency. Which would strike as an issue when installing `audio-speaker`.

So I need opinions on what way we should take this. @dfcreative @jamen 😄

**Comment by jamen** [comment]
Hey.  So I'm all up for using `nan` instead of `node-addon-api` if we can get something `npm install`-able out there faster.   My only concern is I just don't want it to feel like a wasted effort, because NAPI may not be unstable for _that_ long, and there is still things to do on the NAPI branch in the meantime.

I'll let you make the decision on where to invest your time, though.

**Comment by dfcreative** [comment]
As for me I would choose getting things done rather than perfectly undone. That is if we can release this API within one-day effort but with `nan` that is perfectly fine, rather than if we start using `node-addon-api` and stuck for months due to some unimplemented/unstable feature.

But we have always to be open to refactoring, ie. breaking API later to allow for `node-addon-api` is good, actually even better than getting stuck with refactoring now.

**Comment by connorhartley** [comment]
Cool, I'll get it released for `nan` then.

**Comment by connorhartley** [comment]
Do we still want the browser implementation in 2.0? @dfcreative @jamen

**Comment by dfcreative** [comment]
@connorhartley yes, but I can take care of it

**Comment by connorhartley** [comment]
@dfcreative If you would like to make some tests for it that would be sweet! I am working in the release-2.0-browser branch, should be nearly ready. 😄

**Comment by dfcreative** [comment]
@connorhartley I've added minimal easy-peasy test for browser and covered browser implementation here https://github.com/audiojs/audio-speaker/commit/944f25499e777e4082583700fbbef9b326becc05.
Working on [audio-oscillator](https://github.com/audiojs/audio-oscillator) by your request now.

**Comment by connorhartley** [comment]
Thank you very much @dfcreative !

**Comment by iwasrobbed** [comment]
Any chance I can test this out? I'm building an Electron app w/ node for streaming Amazon Polly speech mp3's

**Comment by jamen** [comment]
@iwasrobbed That sounds awesome, feel free to keep us updated!

There is a pull request open at #44 where most of this is implemented already, if I'm not mistaken.  I think the concern at the moment is how stable #44 actually is, I think we need more extensive testing, but I'm unable to check this at the moment (more could have been added since I've looked at it)

@connorhartley @dfcreative, what else needs to be done to wrap this up?  :smile: 

(P.S., if you are decoding with audio.js too, you might also want to see https://github.com/audiojs/audio-decode/issues/2)

**Comment by iwasrobbed** [comment]
Thanks @jamen ; I gave it a quick test drive, but doesn't seem quite ready yet:

>Uncaught Error: Cannot find module '/Users/rob/blah/node_modules/audio-mpg123/lib/audio_mpg123.node'

Let me know if I can help test when you're ready and happy to do so

**Comment by connorhartley** [comment]
We haven't added a prebuilt macos version to the releases as we have been struggling to find someone with macos to help us build it. Did it attempt to build it manually? Were there any errors involved with compiling the binding? If this continues, do you think you could open a separate issue for this? Thanks for your help. 😄
